/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

import { BaseCommand } from '../../deps.ts'
import { Color, Style } from '../types.ts'
import Config from '../Config.ts'
import { Uninstaller } from '../utils/Uninstaller.ts'

export class UninstallCommand extends BaseCommand {

  constructor () {

    super()

    this.description('Remove a module')
      .arguments('[module...:string]')
      .action(async (options, args) => {

        await this.runCommand(args)

      })

  }

  async runCommand (modules: Array<string>) {

    console.log(`======== ${ Color.Cyan }dpm${ Style.Reset } v${ Config.version } ========`)

    for(const module in modules) {

      const uninstaller = new Uninstaller(modules[module], Deno.cwd())

      await uninstaller.removeModule()

    }

  }

}