/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

import { Command } from '../deps.ts'

export class DpmCommand extends Command {

  constructor () {

    super()

    this.name('dpm')
      .version('0.0.1')
      .description('Deno Package Manager. A 3rd party package manager for Deno.')
      .action((options, script: string, additionalArgs: string[]) => {

        console.log(options, script, additionalArgs)
        console.log('test')

      })
      .reset()

  }

}